name: Deploy
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy to Lambda
      run: |
        npm install
        npx esbuild ./*.ts --bundle --platform=node --outdir=dist --external:@aws-sdk
        cd dist
        zip -r lambda.zip * > /dev/null
        aws lambda update-function-code --function-name heythisischris${{ github.ref != 'refs/heads/master' && '-staging' || '' }} --zip-file fileb://lambda.zip > /dev/null
